### ISSUE TITLE
Improvements to CSS code formatting.

### ISSUE THREAD

**Issue by josephtkim** [klaurenjerchau/prj-rev-bwfs-dasmoto#4]
Try to always stay consistent with the formatting of your code. Here is how you might clean up the CSS code to follow consistent formatting with best practices,

```css
h1 {
  font-family: Helvetica;
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}

h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}

h2#brushes {
  background-color: mediumspringgreen;
}

h2#frames {
  background-color: lightcoral;
}

h2#paint {
  background-color: skyblue;
}

h3 {
  font-family: Helvetica;
}

p {
  font-family: Helvetica;
}
```
