### ISSUE TITLE
Simplify the CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [klaurenjerchau/prj-rev-bwfs-dasmoto#5]
When there are multiple elements that share properties, it is a good idea to simplify by applying shared properties to them at once. The font-family property is shared by many elements, so you can simplify like so

```css
h1, h2, h3, p {
  font-family: Helvetica;
}
```
